export const JOIN_SUCCESS = 'JOIN_SUCCESS';
export const JOIN_FAIL = 'JOIN_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const RESEND_PASSWORD = 'RESEND_PASSWORD';
export const RESEND_PASSWORD_FAIL = 'RESEND_PASSWORD_FAIL';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const FETCH_POST = 'FETCH_POST';

export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_FAIL = 'GET_POSTS_FAIL';
export const GET_POSTS_COMPLETE = 'GET_POSTS_COMPLETE';

export const GET_POST_DETAIL_SUCCESS = 'GET_POST_DETAIL_SUCCESS';
export const GET_POST_DETAIL_FAIL = 'GET_POST_DETAIL_FAIL';

export const SEARCH_QUERY = 'SEARCH_QUERY';
export const SEARCH_POST_SUCCESS = 'SEARCH_POST_SUCCESS';

export const FETCH_PROFILE = 'FETCH_PROFILE';

export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL';

export const USER_POSTS_SUCCESS = 'USER_POSTS_SUCCESS';
export const USER_POSTS_FAIL = 'USER_POSTS_FAIL';
export const USER_POSTS_COMPLETE = 'USER_POSTS_COMPLETE';

export const SW_INIT = 'SW_INIT';
export const SW_UPDATE = 'SW_UPDATE';